<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/11
 * Time: 17:18
 */

namespace app\index\controller;


use app\common\lib\Spider;
use app\common\model\Users;
use think\Controller;
use think\Request;
use think\Session;
use think\Cache;

class AuthBase extends Controller
{
    /**
     * 登录用户基本信息
     * @var array
     */
    public $user=[];

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        //蜘蛛来访存入
        Spider::getInstance()->store();

        //判断是否登录
        $this->isLogin();
    }

    /*
     * 判断是否登录
     */
    private function isLogin()
    {
        $user_id=Session::get('user_id');

        if(empty($user_id)){
            return false;
        }

        $user=Users::find($user_id);

        if(empty($user) || $user->is_use != 1){
            return false;
        }

        $this->user=$user;
        return true;
    }
}