<?php
/**
 * Created by PhpStorm.
 * User: zgl
 * Date: 2018/5/23
 * Time: 21:13
 */

namespace app\api\controller\v1;


use app\api\controller\Common;
use app\common\lib\Aes;
use app\common\lib\exception\ApiException;
use app\common\model\User;


/**
 * 客户端Auth基础类库
 * 1.每个接口都需要去集
 * 2.判定access_user_token是否合法
 * 3.用户信息-》user
 * Class AuthBase
 * @package app\api\controller\v1
 */
class AuthBase extends Common
{
    /**
     * 登录用户基本信息
     * @var array
     */
    public $user=[];

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        if(empty($this->isLogin())){
            throw new ApiException('未登录',401);
        }


        /*if(Request::instance()->isAjax()){

            throw new ApiException('未登录',401);

            $res=[
                'status'=>2,
                'info'=>'请先登录'
            ];
            return $res;
        }else{
            $this->redirect('login/index');
        }*/

    }

    //判断是否登录
    public function isLogin()
    {
        if(empty($this->headers['access_usr_token'])){
            return false;
        }

        $aes = new Aes();
        $token=$aes->decrypt($this->headers['access_usr_token']);
        if(empty($token)){
            return false;
        }

        if(!preg_match('/&&/',$token)){
            return false;
        }

        list($token,$id)=explode('&&',$token);
        $user=User::get(['token'=>$token]);
        if(!$user || $user->status != 1){
            return false;
        }

        //判断时间是否过期
        if(time()>$user->time_out){
            return false;
        }

        $this->user=$user;
        return true;
    }
}